INSERT INTO [User] ([Login], Pwd)
VALUES 
('ivanov@example.com', 'qElP!57'),  -- почта Иванова
('petrova@example.com', '0i#s9U'),  -- почта Петровой
('sidorov@example.com', '1yVEO@'),  -- почта Сидорова
('kovalenko@example.com', 'J@Q#3r'),  -- почта Коваленко
('smirnov@example.com', 'pH$Jh9'),  -- почта Смирнов
('Kozlova@example.com', 'iEmkF!3Q'),  -- почта Козлова
('Vasiliev@example.com', 'eEXG6bl!'),  -- почта Васильев
('zaitseva@example.com', 'e2kL6d%'),  -- почта Зайцева
('Pavlov@example.com', '3ETMoV!'),  -- почта Павлов
('Ignatieva@example.com', 'VT#SW4C'),  -- почта Игнатьева
('Sergeev@example.com', 'dRjtc!8V'),  -- почта Сергеев
('Fedorova@example.com', '2pLjOs@'),  -- почта Федорова
('Maximov@example.com', 'TIN%wj2'),  -- почта Максимов
('Filippova@example.com', 'Kx@x7m'),  -- почта Филиппова
('grigoriev@example.com', 'lX!@3WI'),  -- почта Григорьев
('polyakova@example.com', 'VfwG7!aG'),  -- почта Полякова
('Denisov@example.com', 'RXW87r@'),  -- почта Денисов
('Kalinina@example.com', 'Zn9P@z'),  -- почта Калинина
('Mikhailov@example.com', 'OlbD!1W'),  -- почта Михайлов
('Antonova@example.com', 'Y4SqM!U'),  -- почта Антонова
('Kuznetsov@example.com', 'Ktw@1kRY'),  -- почта Кузнецов
('Sokolova@example.com', 'E@I0i8'),  -- почта Соколова
('Timofeev@example.com', 'zQSIa$'),  -- почта Тимофеев
('Nikolaeva@example.com', '8ZSsi?'),  -- почта Николаева
('Gerasimov@example.com', 'ENsG5*'),  -- почта Герасимов
('orlova@example.com', 'Lt#f2pt'),  -- почта Орлова
('Konstantinov@example.com', 'cENj2$WX'),  -- почта Константинов
('Semenova@example.com', 'N*7h9#'),  -- почта Семенова
('Evgeniev@example.com', 'qYd6A#'),  -- почта Евгеньев
('Alexandrova@example.com', '4wD9va!');  -- почта Александрова